spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whereismyhome3?serverTimezone=UTC&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
  mail:
    host: smtp.gmail.com
    port: 587
    username: project534900
    password: vufykbyvgkxxlrkm
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE